{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0235eff8-adc4-4d9a-b474-cfc4ce619b30",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\n",
    "import rclpy\n",
    "from rclpy.node import Node\n",
    "\n",
    "from std_msgs.msg import Int16\n",
    "from geometry_msgs.msg import Twist\n",
    "\n",
    "import serial\n",
    "import threading\n",
    "\n",
    "\n",
    "class ArduinoSerialBridge(Node):\n",
    "    def __init__(self):\n",
    "        super().__init__('arduino_serial_bridge')\n",
    "\n",
    "        # Change this port according to your Arduino port\n",
    "        # Linux example: /dev/ttyACM0 or /dev/ttyUSB0\n",
    "        # Windows example: COM3\n",
    "        self.serial_port = '/dev/ttyACM0'\n",
    "        self.baud_rate = 115200\n",
    "\n",
    "        self.arduino = serial.Serial(\n",
    "            self.serial_port,\n",
    "            self.baud_rate,\n",
    "            timeout=1\n",
    "        )\n",
    "\n",
    "        self.left_ticks_pub = self.create_publisher(Int16, 'left_ticks', 10)\n",
    "        self.right_ticks_pub = self.create_publisher(Int16, 'right_ticks', 10)\n",
    "\n",
    "        self.cmd_vel_sub = self.create_subscription(\n",
    "            Twist,\n",
    "            'cmd_vel',\n",
    "            self.cmd_vel_callback,\n",
    "            10\n",
    "        )\n",
    "\n",
    "        self.get_logger().info('Arduino Serial Bridge Started')\n",
    "        self.get_logger().info(f'Connected to {self.serial_port} at {self.baud_rate}')\n",
    "\n",
    "        self.serial_thread = threading.Thread(target=self.read_from_arduino)\n",
    "        self.serial_thread.daemon = True\n",
    "        self.serial_thread.start()\n",
    "\n",
    "    def cmd_vel_callback(self, msg):\n",
    "        linear = msg.linear.x\n",
    "        angular = msg.angular.z\n",
    "\n",
    "        command = f'CMD,{linear},{angular}\\n'\n",
    "        self.arduino.write(command.encode())\n",
    "\n",
    "        self.get_logger().info(\n",
    "            f'Sent to Arduino: linear={linear}, angular={angular}'\n",
    "        )\n",
    "\n",
    "    def read_from_arduino(self):\n",
    "        while rclpy.ok():\n",
    "            try:\n",
    "                line = self.arduino.readline().decode(errors='ignore').strip()\n",
    "\n",
    "                if line.startswith('TICKS,'):\n",
    "                    data = line.split(',')\n",
    "\n",
    "                    if len(data) == 3:\n",
    "                        left_ticks = int(data[1])\n",
    "                        right_ticks = int(data[2])\n",
    "\n",
    "                        left_msg = Int16()\n",
    "                        right_msg = Int16()\n",
    "\n",
    "                        left_msg.data = left_ticks\n",
    "                        right_msg.data = right_ticks\n",
    "\n",
    "                        self.left_ticks_pub.publish(left_msg)\n",
    "                        self.right_ticks_pub.publish(right_msg)\n",
    "\n",
    "                        self.get_logger().info(\n",
    "                            f'Left Ticks: {left_ticks}, Right Ticks: {right_ticks}'\n",
    "                        )\n",
    "\n",
    "            except Exception as e:\n",
    "                self.get_logger().error(f'Serial read error: {e}')\n",
    "\n",
    "\n",
    "def main(args=None):\n",
    "    rclpy.init(args=args)\n",
    "\n",
    "    node = ArduinoSerialBridge()\n",
    "\n",
    "    try:\n",
    "        rclpy.spin(node)\n",
    "    except KeyboardInterrupt:\n",
    "        pass\n",
    "\n",
    "    node.arduino.close()\n",
    "    node.destroy_node()\n",
    "    rclpy.shutdown()\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
